---
- hosts: all
  become: true
  become_user: root

  tasks:

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Perform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes