---
- hosts: all
  gather_facts: true
  become: true
  tasks:
      - name: gather os specific variables
        include_vars: "{{ item }}"
        with_first_found:
            - "vars/{{ ansible_distribution }}.yaml"

      - set_fact:
        home: "{{ lookup('env', 'HOME') }}"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url}}"
            dest: "{{ home }}/zabbix.deb"

      - name: Recursively find {{ home }} files younger than 2 days
        ansible.builtin.find:
          paths: "{{ home }}"
          age: -2d
          recurse: yes

      - name: Install zabbix repo
        become: true
        apt:
            deb: "{{ home }}/zabbix.deb"
            state: present

      - name: Install zabbix agent2
        become: true
        apt:
            name: zabbix-agent2
            state: present
            update_cache: yes

      - name: Stop service zabbix-agent2
        become: true
        service:
            name: zabbix-agent2
            state: stopped

      - name: Remove zabbix config file
        become: true
        file:
            path: /etc/zabbix/zabbix_agent2.conf
            state: absent

      - name: Create new zabbix config file from template
        become: true
        template:
            src: "templates/zabbix_agent2.conf.j2"
            dest: "/etc/zabbix/zabbix_agent2.conf"

      - name: Start service zabbix-agent2
        become: true
        service:
            name: zabbix-agent2
            state: started