---
- hosts: all
  gather_facts: true
  tasks:
    - name: Verify if we have sudo access
      become: true
          command: id -u
          register: id_output

    - name: Assert output
      assert:
        that: id_output.stdout == '0'

      - name: gather os specific variables
        include_vars: "{{ item }}"
        with_first_found:
            - "vars/{{ ansible_distribution }}.yaml"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url}}"
            dest: /tmp/zabbix.deb

      - name: Install zabbix repo
        become: yes
        apt:
            deb: /tmp/zabbix.deb
            state: present

      - name: Install zabbix agent
        become: yes
        apt:
            name: zabbix-agent2
            state: present
            update_cache: yes

      - name: Remove zabbix config file
        become: yes
        file:
            path: /etc/zabbix/zabbix_agentd.conf
            state: absent

      - name: Create new zabbix config file from template
        become: yes
        template:
          src: template/zabbix_agent2.conf.j2
          dest: /etc/zabbix/zabbix_agent2.conf

      - name: Restart service zabbix-agent2
        service:
            name: zabbix-agent2
            state: restarted