---
- hosts: all
  gather_facts: true
  become_user: root
  become: true
  tasks:
      - name: gather os specific variables
        include_vars: "{{ item }}"
        with_first_found:
            - "vars/{{ ansible_distribution }}.yaml"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url}}"
            dest: "/tmp/zabbix.deb"
            force: yes

      - name: Install zabbix repo
        become: yes
        # become_method: sudo
        # apt:
        #     deb: "/tmp/zabbix.deb"
        #     state: present
        shell: sudo dpkg --force-confdef --force-confold -i /tmp/zabbix.deb
        register: command_output_install_zabbix
    
      - name: Show install zabbix repo output
        debug:
          var: command_output_install_zabbix.stdout_lines

      - name: Remove apt lock file
        file:
            state: absent
            path: "/var/lib/dpkg/lock-frontend"

      - name: Remove apt list lock file
        file:
            state: absent
            path: "/var/lib/apt/lists/lock"

      - name: Update apt Cache
        shell: sudo apt update
        register: cmd_out_apt_update

      - name: Show apt update output
        debug:
          var: cmd_out_apt_update.stdout_lines
        
      - name: Remove apt lock file
        file:
            state: absent
            path: "/var/lib/dpkg/lock-frontend"

      - name: Remove apt list lock file
        file:
            state: absent
            path: "/var/lib/apt/lists/lock"

      - name: Wait for APT Lock
        shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

      - name: Install zabbix agent2
        shell: sudo apt install zabbix-agent2 zabbix-agent2-plugin-*
        register: cmd_out_zabbix_install

      - name: Show install zabbix packages output
        debug:
          var: cmd_out_zabbix_install.stdout_lines

      - name: Stop service zabbix-agent2
        service:
            name: zabbix-agent2
            state: stopped

      - name: Remove zabbix config file
        file:
            path: /etc/zabbix/zabbix_agent2.conf
            state: absent

      - name: Create new zabbix config file from template
        template:
            src: "templates/zabbix_agent2.conf.j2"
            dest: "/etc/zabbix/zabbix_agent2.conf"

      - name: Start service zabbix-agent2
        service:
            name: zabbix-agent2
            state: started