---
- hosts: all
  gather_facts: true
  #become_user: root
  remote_user: wk
  become: true
  tasks:
      - name: gather os specific variables
        include_vars: "{{ item }}"
        with_first_found:
            - "vars/{{ ansible_distribution }}.yaml"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url}}"
            dest: "/tmp/zabbix.deb"
            force: yes
        register: cmd_out_download_zabbix_repo

      - name: Show apt update output
        debug:
          var: cmd_out_download_zabbix_repo.stdout_lines

      - name: Install zabbix repo
        shell: sudo dpkg --force-confdef --force-confold -i /tmp/zabbix.deb
        register: cmd_out_install_zabbix_repo
    
      - name: Show install zabbix repo output
        debug:
          var: cmd_out_install_zabbix_repo.stdout_lines

      - name: Update apt Cache
        shell: sudo apt update
        register: cmd_out_apt_update

      - name: Show apt update output
        debug:
          var: cmd_out_apt_update.stdout_lines

      - name: Install zabbix agent2
        shell: sudo apt install zabbix-agent2 zabbix-agent2-plugin-*
        register: cmd_out_zabbix_install

      - name: Show install zabbix packages output
        debug:
          var: cmd_out_zabbix_install.stdout_lines

      - name: Remove zabbix config file
        shell: sudo rm -rf /etc/zabbix/zabbix_agent2.conf
        register: cmd_out_remove_conf

      - name: Show remove zabbix config output
        debug:
          var: cmd_out_remove_conf.stdout_lines

      # - name: Create new zabbix config file from template
      #   shell: sudo cp template/zabbix_agent2.conf.j2 /etc/zabbix/zabbix_agent2.conf
      #   register: cmd_out_copy_template

      - name: Create new zabbix config file from template
        template:
          src: template/zabbix_agent2.conf.j2
          dest: /etc/zabbix/zabbix_agent2.conf

      - name: Show copy template output
        debug:
          var: cmd_out_copy_template.stdout_lines

      - name: Start service zabbix-agent2
        become_user: root
        become: true
        service:
            name: zabbix-agent2
            state: restarted